scrape_configs:
  - job_name: 'publicdnsping'
    scrape_interval: 1m
    scrape_timeout: 5s
    metrics_path: /probe
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - 1.1.1.1    # Target to probe with http.
        - 1.0.0.1   # Target to probe with https.
        - 8.8.8.8 # Target to probe with http on port 8080.
        - 8.8.4.4
        - 2606:4700:4700::64
        - 2606:4700:4700::6400
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
        - 209.244.0.3
        - 209.244.0.4
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'rootdnspingv4'
    scrape_interval: 1m
    scrape_timeout: 5s
    metrics_path: /probe
    params:
      module: [icmpv4]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - a.root-servers.net
        - b.root-servers.net
        - c.root-servers.net
        - d.root-servers.net
        - e.root-servers.net
        - f.root-servers.net
        - g.root-servers.net
        - h.root-servers.net
        - i.root-servers.net
        - j.root-servers.net
        - k.root-servers.net
        - l.root-servers.net
        - m.root-servers.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'rootdnspingv6'
    scrape_interval: 1m
    scrape_timeout: 5s
    metrics_path: /probe
    params:
      module: [icmpv6]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - a.root-servers.net
        - b.root-servers.net
        - c.root-servers.net
        - d.root-servers.net
        - e.root-servers.net
        - f.root-servers.net
        - g.root-servers.net
        - h.root-servers.net
        - i.root-servers.net
        - j.root-servers.net
        - k.root-servers.net
        - l.root-servers.net
        - m.root-servers.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
